// <auto-generated />
namespace KotareMonopoly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_hours : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_hours));
        
        string IMigrationMetadata.Id
        {
            get { return "201505220012507_add_hours"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
